Repository projectsyn/component-ingress-nginx, pull requests merged in 2022-04, with the labels that each got.

#25 Rename the helm chart release_name variable for Kapitan to name
  class/ingress-nginx.yml
Labels: dependency

#27 Add parameter to specify the kubernetes version
  class/ingress-nginx.yml
  docs/modules/ROOT/pages/references/parameters.adoc
  tests/defaults.yml
Labels: bug, breaking

#28 Add missing documentation for upgrade to 3.x
  docs/modules/ROOT/pages/how-tos/upgrade-2.x-to-3.x.adoc
  docs/modules/ROOT/partials/nav.adoc
Labels: documentation
